apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskmanager.fullname" . }}-db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ include "taskmanager.name" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "taskmanager.name" . }}-db
    spec:
      containers:
      - name: db
        image: {{ .Values.db.image }}
        ports:
        - containerPort: {{ .Values.db.service.port }}
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: SA_PASSWORD
        - name: ACCEPT_EULA
          value: "Y"
        volumeMounts:
        - name: sql-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: sql-storage
        persistentVolumeClaim:
          claimName: {{ include "taskmanager.fullname" . }}-db-pvc